# travis.CI YML config file

language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  
# install dependencies
install:
  - pip install pyspeedtest urllib3
  - pip install pyinstaller  # only for compiling here, not needed
  
# do it!
script:
  - make all